### ISSUE TITLE
"Failed To Move From Temporary Path To /Themes" Error For Specific Themes

### ISSUE THREAD

**Issue by Pepy550** [ErmanSayin/Themely#67] opened 2017-06-11 07:53 UTC
I'm using the 46e000c-git nightly build right now and when I try to download these specific themes (https://3dsthem.es/13329, https://3dsthem.es/13187 and https://3dsthem.es/6283) via QR Code, I get an error for moving to temporary path from /Themes. Downloading all the other themes works fine, I tried reinstalling the build and the same error happens..

**Comment by ErmanSayin** [comment] 2017-06-15 11:46
Duplicate of #54.

**Closed by ErmanSayin** 2017-06-15 11:46 UTC
Labels: duplicate
