### ISSUE TITLE
Themely 1.4.0 not working/crashing (yellow screen) on RPGHax/SteelHax

### ISSUE THREAD

**Issue by AlwayzNick** [ErmanSayin/Themely#123] opened 2017-08-23 10:34 UTC
Hello,

If i try to open Themely on my o3dsxl trough Homebrew. I am on firmware 11.5.0-38E and the .dsx file so i can open it with homebrew. But when i do that (doesn't matter if i use RPG or Steelhax) it get stuck on the yellow screen.
Hope you got a solution to this.

**Comment by ErmanSayin** [comment] 2017-08-23 17:15
Duplicate of #121

**Closed by ErmanSayin** 2017-08-23 17:15 UTC
