### ISSUE TITLE
Themely 1.4.0 not working

### ISSUE THREAD

**Issue by That1Guy20XX** [ErmanSayin/Themely#118] opened 2017-08-21 00:33 UTC
I'm on 11.4 with Homebrew and no CFW using Themely v1.4.0, but I get a red screen when I start it. Did I do something wrong?

**Comment by sks316** [comment] 2017-08-21 02:04
You could try redownloading Themely 1.4.0.
Which entrypoint are you using? Which system model?

**Comment by That1Guy20XX** [comment] 2017-08-21 02:34
New 3DS, using Freakyhax.

**Comment by That1Guy20XX** [comment] 2017-08-21 02:46
Even redownloading doesn't work.

**Comment by ErmanSayin** [comment] 2017-08-21 10:49
Duplicate of #99. Make sure your payload is updated.

**Closed by ErmanSayin** 2017-08-21 10:49 UTC

**Comment by That1Guy20XX** [comment] 2017-08-22 04:30
Themely 1.4.0 still doesn't work. Updated payload with RPwnG or not. Even redownloading again won't work.
