### ISSUE TITLE
Themely don´t start

### ISSUE THREAD

**Issue by AngelOscuro20** [ErmanSayin/Themely#133] opened 2017-08-27 17:37 UTC
I test the versions 1.4.1, 1.4.0, 1.3.3, 1.32, 1.3.1, 1.3.0 on homebrew launcher 2.0(with the last payloads)l,in a 3ds on 1.15 with Rpghax and stickerhax and always when I start Themely gets stuck in a bottom yellow screen. How i can fix it?

**Comment by ErmanSayin** [comment] 2017-08-27 17:41
Duplicate of #121

**Closed by ErmanSayin** 2017-08-27 17:41 UTC
