### ISSUE TITLE
Some themes aren't alphabetically ordered correctly

### ISSUE THREAD

**Issue by sks316** [ErmanSayin/Themely#22] opened 2017-04-30 04:08 UTC
For example, my Sonic the Hedgehog theme was not with the other themes beginning with S. Instead, it was at the very bottom of the list along with a few other incorrectly ordered themes.

**Comment by ErmanSayin** [comment] 2017-04-30 07:59
Duplicate of #11.

**Closed by ErmanSayin** 2017-04-30 07:59 UTC
Labels: duplicate
